### ISSUE TITLE
a bug in the recWalk function of merkletree.ts

### ISSUE THREAD

**Issue by skardas** [iden3/js-merkletree#34]
It goes infinite recursion. 
await this.**walk**((n as NodeMiddle).childL, f);
await this.**walk**((n as NodeMiddle).childR, f);

fix: change line 452 and 453 to
await this.**recWalk**((n as NodeMiddle).childL, f);
await this.**recWalk**((n as NodeMiddle).childR, f);

**Comment by perseus34x** [comment]
await this.walk(rootKey, f);
                   ^

RangeError: Maximum call stack size exceeded


RangeError: Maximum call stack size exceeded
    at Object.get [as bytesEqual] (node_modules/@iden3/js-merkletree/dist/cjs/lib/utils/index.js:6:47)
    at Merkletree.walk (node_modules/@iden3/js-merkletree/src/lib/merkletree/merkletree.ts:461:9)
    at Merkletree.walk (node_modules/@iden3/js-merkletree/src/lib/merkletree/merkletree.ts:464:16)
    at Merkletree.walk (node_modules/@iden3/js-merkletree/src/lib/merkletree/merkletree.ts:464:16)

**Comment by vmidyllic** [comment]
fixed in #36
